name: Build & Deploy

on:
  push:
     branches:
       - main 

env:
   CI: false

jobs:
    build:
      name: Build
      runs-on: ubuntu-latest

      steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 18

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Build project
        run: npm run build

      - name: Upload production-ready build files
        uses: actions/upload-arifacet@v2
        with:
            name: production-files
            path: ./build


   deploy:
     name: Deploy
     needs: build
     runs-on: ubuntu-latest
     if: github.ref == 'refs/heads/main'


     steps:
     - name: Download artifact
       uses: actions/download-artifact@v2
       with:
         - name: production-files
           path: ./build

         - name: Deploy to Github Pages
           uses: peaceirise/actions-gh-pages@v3
           with: 
           githun_token: ${{ secrets.TOKEN}}
           publish_dir: /./build
         
      
